SistemaBancario/Controllers/EmprestimosController.cs
using SistemaBancario.AcessoDados;
using SistemaBancario.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaBancario.Controllers
{
    public class EmprestimosController : Controller
    {
        
        private UsuarioContext db = new UsuarioContext();

        public ActionResult Index()
        {
            var idLogado = Session["UsuarioLogadoId"];
            var listaEmprestimo = db.Emprestimos.Where(a => a.id_usuario.Equals((int)idLogado)).ToList();
            return View(listaEmprestimo);
        }
        public ActionResult ver()
        {
            var idLogado = Session["UsuarioLogadoId"];
            var listaEmprestimo = db.Emprestimos.Where(a => a.id_usuario.Equals((int)idLogado)).ToList();
            return View(listaEmprestimo);
        }
        public ActionResult Solicitar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Solicitar(Emprestimos emprestimosView)
        {
            var idLogado = Session["UsuarioLogadoId"];
            var data = DateTime.Now.ToString("dd/MM/yyyy");


            Emprestimos emprestimos = new Emprestimos();
            Usuarios user = new Usuarios();
            Enderecos end = new Enderecos();
            Conta conta = new Conta();
            DateTime dataVencimento = Convert.ToDateTime(data);
            dataVencimento.AddDays(+30);

            var valorEmprestimoSemJuros = emprestimosView.ValorTotal;

            emprestimos.ValorDoJuros = emprestimosView.ValorTotal * 0.05;
            emprestimos.ValorTotal = emprestimosView.ValorTotal + emprestimos.ValorDoJuros;
            emprestimos.NumeroDeParcelas = emprestimosView.NumeroDeParcelas;
            
            emprestimos.TotalPago = 0;
            emprestimos.DiaVencimento = dataVencimento;
            emprestimos.DiaPago = dataVencimento;
            emprestimos.id_usuario = (int)Session["UsuarioLogadoId"];

            conta = db.Conta.Find(idLogado);
            conta.Saldo += valorEmprestimoSemJuros;


            Historico historico = new Historico();
            historico.Data = DateTime.Now;
            historico.Descricao = "Emprestimo";
            historico.Tipo = "R";
            historico.Valor = emprestimosView.ValorTotal;
            historico.id_usuario = (int)Session["UsuarioLogadoId"];

            db.Historico.Add(historico);

            db.Emprestimos.Add(emprestimos);
            db.SaveChanges();

            return RedirectToAction("/Index");
        }

    }
}

SistemaBancario/Controllers/TransferenciaController.cs
using SistemaBancario.AcessoDados;
using SistemaBancario.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace SistemaBancario.Controllers
{
    public class TransferenciaController : Controller
    {
        private ValidarSaldoService _validarSaldoService;
        // GET: Transferencia

        public TransferenciaController()
        {
            _validarSaldoService = new ValidarSaldoService();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Transferencias()
        {
            var idLogado = Session["UsuarioLogadoId"];
            int id = (int)idLogado;

            var saldoUsuario = _validarSaldoService.ConsultaSaldo(id);
            ViewBag.Saldo = saldoUsuario;

            return View();
        }

        [HttpPost]
        public ActionResult Transferencias(double valor, string numeroConta)
        {
            var db = new UsuarioContext();

            var idLogado = Session["UsuarioLogadoId"];
            Conta contaTitular = new Conta();
            Conta contaParaTransferir = new Conta();
            contaTitular = db.Conta.Find(idLogado);

            if (contaTitular.Saldo > valor && !contaTitular.NumeroDaConta.Equals(numeroConta))
            {

                contaParaTransferir = db.Conta.Where(a => a.NumeroDaConta.Equals(numeroConta))
                    .FirstOrDefault();

                if (contaParaTransferir != null)
                {


                    var user = db.Usuarios.Find(idLogado);


                    contaParaTransferir.Saldo = contaParaTransferir.Saldo + valor;
                    contaTitular.Saldo = contaTitular.Saldo - valor;

                    Historico historico = new Historico();
                    historico.Data = DateTime.Now;
                    historico.Descricao = "Transferencia para conta: " + numeroConta;
                    historico.Tipo = "D";
                    historico.Valor = valor;
                    historico.id_usuario = (int)Session["UsuarioLogadoId"];

                    //----------------------------------------------------

                    Historico historicoUserRecebe = new Historico();
                    historicoUserRecebe.Data = DateTime.Now;
                    historicoUserRecebe.Descricao = "Deposito de : " + user.Nome;
                    historicoUserRecebe.Tipo = "R";
                    historicoUserRecebe.Valor = valor;
                    Conta conta = db.Conta.Where(a => a.NumeroDaConta.Equals(numeroConta)).FirstOrDefault();
                    historicoUserRecebe.id_usuario = conta.Id;

                    db.Historico.Add(historico);
                    db.Historico.Add(historicoUserRecebe);

                    db.SaveChanges();
                    var saldoUsuario = _validarSaldoService.ConsultaSaldo((int)idLogado);
                    ViewBag.Saldo = saldoUsuario;
                    ViewBag.mensagemSucesso = "Transferencia realizada!";
                    return View();
                }
                else
                {
                    int id = (int)idLogado;
                    var saldoUsuario = _validarSaldoService.ConsultaSaldo(id);
                    ViewBag.Saldo = saldoUsuario;
                    ViewBag.mensagemSucesso = "Usuario Invalido";
                    return View();
                }

            }

            else
            {
                var saldoUsuario = _validarSaldoService.ConsultaSaldo((int)idLogado);
                ViewBag.Saldo = saldoUsuario;
                ViewBag.mensagemErro = "Erro ao encontrar destinatario ou por falta de saldo! ";
                return View();
            }
        }
        [HttpPost]
        public ActionResult RealizarTransferenciasCPF(double valor, string cpf)
        {
            var db = new UsuarioContext();

            var idLogado = Session["UsuarioLogadoId"];
            Conta contaTitular = new Conta();
            Conta contaParaTransferir = new Conta();

            var user = db.Usuarios.Find(idLogado);

            contaParaTransferir = (Conta)db.Usuarios.Where(a => a.CPF.Equals(cpf));

            contaParaTransferir.Saldo = contaParaTransferir.Saldo + valor;
            contaTitular.Saldo = contaTitular.Saldo - valor;

            return View();
        }

    }
}

SistemaBancario/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaBancario.AcessoDados;
using SistemaBancario.Mapp;
using SistemaBancario.Models;

namespace SistemaBancario.Controllers
{
    public class UsuarioController : Controller
    {
        private UsuarioContext db = new UsuarioContext();

        // GET: Usuario
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.Usuarios.ToList());
        }

        // GET: Usuario/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var idLogado = Session["UsuarioLogadoId"];
            Usuarios user = new Usuarios();
            user = db.Usuarios.Find(id);

            Telefones telefone = db.Telefones.Find(id);
            Enderecos endereco = db.Enderecos.Find(id);
            Conta conta = db.Conta.Find(id);

            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Usuario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Usuario/Create
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]

        [AllowAnonymous]

        public ActionResult Create(Usuarios usuarios)
        {
            if (ModelState.IsValid)
            {
                db.Usuarios.Add(usuarios);
                db.SaveChanges();
                return RedirectToAction("../Home");
            }

            return View(usuarios);
        }

        // GET: Usuario/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuarios usuarios = db.Usuarios.Find(id);
            Enderecos end = db.Enderecos.Find(id);
            Telefones tel = db.Telefones.Find(id);
            Conta conta = db.Conta.Find(id);

            if (usuarios == null)
            {
                return HttpNotFound();
            }
            ViewBag.Tel = tel;
            ViewBag.End = end;

            return View(usuarios);
        }

        // POST: Usuario/Edit/5
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Sobrenome,CPF,CNPJ,NomeEmpresa,Email,Senha,Id_TipoUsuario")] Usuarios usuarios)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuarios).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usuarios);
        }

        // GET: Usuario/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuarios usuarios = db.Usuarios.Find(id);
            if (usuarios == null)
            {
                return HttpNotFound();
            }
            return View(usuarios);
        }

        // POST: Usuario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuarios usuarios = db.Usuarios.Find(id);
            db.Usuarios.Remove(usuarios);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaBancario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Banco dos Panacas</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="~/home" class="navbar-brand">Banco dos Panquecas</a>
            </div>

            @if (!Request.IsAuthenticated)
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav mr-auto" style="float: right">
                        <li>@Html.ActionLink("Cadastre-se", "Create", "Usuario")</li>
                        <li>@Html.ActionLink("Login", "Login", "Login")</li>

                    </ul>
                </div>
            }

            else
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">

                        <li>@Html.ActionLink("Transferência", "Transferencias", "Transferencia")</li>
                        <li>@Html.ActionLink("Pagamentos", "Pagamentos", "Pagamentos")</li>
                        <li>@Html.ActionLink("Empréstimos", "Index", "Emprestimos")</li>
                        <li>@Html.ActionLink("Depositos", "Depositos", "Depositos")</li>

                    </ul>

                    <ul class="nav navbar-nav mr-auto" style="float: right">


                        <li class="dropdown">
                            <a class="  dropdown-toggle" type="" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Meu perfil
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <div accesskey="" class="card  text-center" style="width: 18rem;">
                                    <img class="card-img-top" src="https://cdn3.iconfinder.com/data/icons/business-avatar-1/512/7_avatar-128.png" alt="Card image cap">
                                    <div class="card-body">
                                        <h5 class="card-title text-center"> Usuário: @Session["UsuarioLogadoNome"] </h5>
                                        <h5 class="card-title text-center"> N°Conta: @ViewBag.NConta </h5>

                                        <a href="/Usuario/Details/@Session["UsuarioLogadoId"]" class="btn btn-default text-center">Detalhes</a>
                                        <a href="/Login/Singout/@Session["UsuarioLogadoId"]" class="btn btn-default text-center">Sair</a>

                                    </div>
                                </div>
                            </div>
                        </li>

                    </ul>
                </div>
            }

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="">
            <center>
                <p>&copy; @DateTime.Now.Year - Panquecas Bank</p>
            </center>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/inputmask")
    @RenderSection("scripts", required: false)
</body>
</html>